name: pages

on:
  push:
    branches:
      - main
    paths:
      - zine.ziggy
      - layouts/**
      - content/**
      - assets/**
      - flake.nix
      - flake.lock
      - nix/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout Repository
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install Nix Toolchain
        uses: https://github.com/DeterminateSystems/nix-installer-action@v19
      - name: Build Site For Deployment
        run: nix develop -c zine release
      - name: Deploy To Cloudflare Pages
        run: |
          nix develop -c npx wrangler pages deploy public \
            --project-name=website \
            --commit-dirty=true
