name: pages

on:
  push:
    branches:
      - main
    paths:
      - zine.ziggy
      - layouts/**
      - content/**
      - assets/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Setup Zine Toolchain
        uses: https://github.com/kristoff-it/setup-zine@v1
        with: { version: 'v0.10.2' }
      - name: Build Site For Deployment
        run: zine release
      - name: Deploy To Cloudflare Pages
        uses: https://github.com/cloudflare/wrangler-action@v3.12.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=website

