name: pages

on:
  push:
    branches:
      - main
    paths:
      - assets/**/*
      - content/**/*.smd
      - layouts/**/*.shtml
      - .github/workflows/*.yml
      - nix/overlay.nix
      - flake.lock
      - zine.ziggy
      - flake.nix

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      - name: Setup lix toolchain
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease
        with: { extra_nix_config: 'experimental-features = nix-command flakes' }
      - name: Setup nix actions cache
        uses: determinatesystems/magic-nix-cache-action@v13
      - name: Build website with zine
        run: nix develop -c zine release
      - name: Upload static files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: website-${{ github.sha }}
          retention-days: 1
          path: public
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [build]
    steps:
      - name: Download static files
        uses: actions/download-artifact@v5.0.0
        with: { name: 'website-${{ github.sha }}', path: public }
      - name: Deploy to Cloudflare pages
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=website
